name: build_windows

on: [push, pull_request, workflow_dispatch]

jobs:
  windows:
    name: ${{ matrix.config }} Windows ${{ matrix.arch }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64]

    steps:
    - name: Install MSYS2 and Dependencies
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-cmake mingw-w64-x86_64-clang mingw-w64-x86_64-freetype
          make
        path-type: inherit

    - name: Checkout Submodules
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.LIBRARY_ACCESS_TOKEN }}
        submodules: true
        lfs: true

    - name: Checkout LFS objects
      shell: msys2 {0}
      run: git lfs checkout

    - name: Update Engine Submodules
      shell: msys2 {0}
      run: git -C dependencies/engine submodule update --init

    - name: Build
      shell: msys2 {0}
      run: |
        mkdir ./build
        cmake . -B ./build -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -G Unix\ Makefiles
        cmake --build ./build
        cp -r /mingw64/bin/{libstdc++-6.dll,libgcc_s_seh-1.dll,libwinpthread-1.dll}\
              ./build/game

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Windows-${{ matrix.arch }}
        path: build/game/
        if-no-files-found: error
